# Generated by Django 5.1.2 on 2024-10-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("director", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("rating", models.FloatField()),
                ("synopsis", models.TextField()),
                ("poster_url", models.URLField(max_length=255)),
            ],
        ),
    ]
