# Generated by Django 5.1.2 on 2024-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_populate_movies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
