# Generated by Django 5.1.2 on 2024-11-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_watchlater"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
